### PR TITLE
Fix cant redefine

### PR DESCRIPTION
**Pull request by Fristi**
When using the latest SNAPSHOT version I couldn't use IDL imports multiple times. It throw me a:

```
org.apache.avro.SchemaParseException: Can't redefine: Amounts
at org.apache.avro.Schema$Names.put(Schema.java:1128)
	at org.apache.avro.Schema$Names.add(Schema.java:1123)
	at org.apache.avro.Schema.parse(Schema.java:1253)
	at org.apache.avro.Schema.parse(Schema.java:1269)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1032)
	at org.apache.avro.Schema$Parser.parse(Schema.java:997)
	at com.sksamuel.avro4s.ModuleGenerator$$anonfun$fromFiles$1.apply(ModuleGenerator.scala:19)
	at com.sksamuel.avro4s.ModuleGenerator$$anonfun$fromFiles$1.apply(ModuleGenerator.scala:19)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at com.sksamuel.avro4s.ModuleGenerator$.fromFiles(ModuleGenerator.scala:19)
	at com.sksamuel.avro4s.Avro4sSbtPlugin$$anonfun$runAvro2Class$1$$anonfun$apply$8.apply(Avro4sSbtPlugin.scala:85)
	at com.sksamuel.avro4s.Avro4sSbtPlugin$$anonfun$runAvro2Class$1$$anonfun$apply$8.apply(Avro4sSbtPlugin.scala:84)
	at scala.Option.map(Option.scala:145)
	at com.sksamuel.avro4s.Avro4sSbtPlugin$$anonfun$runAvro2Class$1.apply(Avro4sSbtPlugin.scala:84)
	at com.sksamuel.avro4s.Avro4sSbtPlugin$$anonfun$runAvro2Class$1.apply(Avro4sSbtPlugin.scala:70)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This will fix it by creating a Parser for each file. Could you make me a release after a merge 😄  ?

### CODE REVIEW

**Comment by kiara-riley** [comment]
The Parser change breaks the ability for `avsc` files to refer to types from earlier `avsc` files. Not sure how to fix both.

**Comment by kiara-riley** [comment]
So I kind of have an idea of why these two features don't work together. When an avdl file is used as input for the plugin, it gets compiled into a set of avsc files under `resource_managed`. Those files are then compiled into a case class like any old avsc file.

#11 added support for avsc files to refer to another type by name(`{ "name": "fieldName", "type": "namespace.PreviouslyDefinedType" }`). You would think that both would work flawlessly together since the step that is failing is the same for both(both of them are avsc files at this point). The difference is that the avsc files generated from avdl files don't refer to the existing types by name, they instead redefine them as a new type with the same json as they were originally defined. 

I suspect most people aren't doing this in their manually edited avsc files because it would be a huge pain to modify a record in two or more places all the time.

So if this gets merged, it would break any avsc files that refer to existing types by name, but avsc files that instead of referencing types, redefine the types(with same json) will stay working.

I think that the default behavior for avdl files working is probably better but I think both use cases should be supported. I was able to get both to work with some super hacky nonsense that reuses a parser in the avsc file case but creates a new one for each avdl schemata. I think my project that depends on this is planning on going with using avdl files so I am going to see if I can create a better solution that supports both use cases(although I am fairly inexperienced with plugins so I may not figure something out).

**Comment by sksamuel** [comment]
Hi, can you explain that last sentence again. Assume that I'm completely stupid, which I am.

**Comment by kiara-riley** [comment]
Quick example:
Here is another file that 'B' will refer to in two ways:
```
{  
   "name":"A",
   "namespace":"v1",
   "type":"record",
   "fields":[  
      {  
         "type":"int",
         "name":"value"
      },
      {  
         "name":"bool",
         "type":{  
            "type":"enum",
            "name":"Bool",
            "symbols":[  
               "True",
               "False"
            ]
         }
      }
   ]
}
```

Call this case Alpha:
```
{  
   "name":"B",
   "namespace":"v1",
   "type":"record",
   "fields":[  
      {  
         "name":"a",
         "type":"v1.A"
      }
   ]
}
```

Call this case Beta:
```
{  
   "name":"B",
   "namespace":"v1",
   "type":"record",
   "fields":[  
      {  
         "name":"a",
         "type":{  
            "name":"A",
            "type":"record",
            "fields":[  
               {  
                  "type":"int",
                  "name":"value"
               },
               {  
                  "name":"bool",
                  "type":{  
                     "type":"enum",
                     "name":"Bool",
                     "symbols":[  
                        "True",
                        "False"
                     ]
                  }
               }
            ]
         }
      }
   ]
}
```

Alpha refers to the type `A` by reference and Beta refers to the type `A` by repetition. Both seem to work in avro if you handle the `Parser` creation correctly. Reference only works if the two files are loaded into the same `Parser`, `A` before `B`. Repetition only works if the two files are loaded into completely separate `Parser`s, or avro complains with 'Can't redefine: A'.

The `avdl` processing step creates `avsc` files from the `avdl` file. If you have a reference to another type in an `avdl` file, avro uses the repetition method for the referred-to types. This is why this PR was created essentially reversing #11 since that pretty much completely removes one of the best parts of `avdl` files(besides syntax).

We need to handle the two cases in different ways which is what I hope I did decently with #29. My behavior was to allow the reference method for user files and the repetition method for any managed(read as avdl) files.

Maybe that was too much but I hope that clears things up.

**Comment by sksamuel** [comment]
That's a brilliant explanation of the problem thanks. Do you think it would be worthwhile to add a flag to the sbt plugin to allow users to choose which behaviour to pick, defaulting to what your PR does ?

**Comment by kiara-riley** [comment]
Yeah that is probably a good idea in case anyone has existing sources on an old version that they don't want to migrate. I'll get to work on a key for that. Lets continue discussion in #29 if you are cool with it.

**Comment by sksamuel** [comment]
Yep

**Pull request closed without merging**
